mathbase/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.contrib import admin

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^tree/', include('tree.urls', namespace='tree')),
	url(r'^login/', 'django.contrib.auth.views.login', name='login'),
	url(r'^logout/', 'django.contrib.auth.views.logout', {'next_page': '/tree'}, name='logout'),
	url(r'^$', RedirectView.as_view(url='tree/', permanent=False), name='index'),
)

admin.site.site_header = 'MATHBASE administration'
admin.site.site_title = 'MATHBASE admin page'

tree/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from tree import views

urlpatterns = patterns('',
	url(r'^$', views.ListNode.as_view(), name='ListNode'),
	url(r'^node/(?P<pk>\d+)/$', views.ShowNode.as_view(), name='ShowNode'),
	url(r'^node/create/subnodeof/(?P<father>\d+)/$', login_required(views.NodeCreate.as_view()), name='NodeCreate'),
	url(r'^node/(?P<pk>\d+)/edit/$', login_required(views.NodeUpdate.as_view()), name='NodeUpdate'),
	url(r'^node/(?P<pk>\d+)/delete/$', login_required(views.NodeDelete.as_view()), name='NodeDelete'),
	url(r'^link/(?P<pk>\d+)/edit/next/(?P<next>\d+)/$', login_required(views.LinkUpdate.as_view()), name='LinkUpdate'),
	url(r'^link/create/next/(?P<next>\d+)/$', login_required(views.LinkCreate.as_view()), name='LinkCreate'),
	url(r'^link/(?P<pk>\d+)/delete/next/(?P<next>\d+)/$', login_required(views.LinkDelete.as_view()), name='LinkDelete'),
	url(r'^tag/create/next/(?P<next>\d+)/$', login_required(views.TagCreate.as_view()), name='TagCreate'),
)

tree/models.py
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
class Node(models.Model):
	name = models.TextField()
	text = models.TextField()
	parent = models.ForeignKey('Node', null=True, blank=True, related_name='children')
	#deleted = models.BooleanField(editable=False, default=False)

	def __str__(self):
		return str(self.name)

class Link(models.Model):
	name = models.TextField()
	description = models.TextField()
	link = models.URLField(max_length=500)
	added = models.DateField(auto_now_add=True)
	nodes = models.ManyToManyField('Node', related_name='links')
	#deleted = models.BooleanField(editable=False, default=False)
	tags = models.ManyToManyField('Tag', related_name='links')

	def __str__(self):
		return str(self.name) + " - " + str(self.link)

class Tag(models.Model):
	name = models.CharField(max_length=80)
	
	def __str__(self):
		return str(self.name)

tree/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.forms.widgets import TextInput
from models import Node, Link, Tag

class ListNode(ListView):
	model = Node
	
	def get_queryset(self):
		qs = super(ListNode, self).get_queryset()
		return qs.filter(parent=None)

class ShowNode(DetailView):
	model = Node
	
	def get_context_data(self, **kwargs):
		context = super(ShowNode, self).get_context_data(**kwargs)
		context['latest_added'] = Link.objects.order_by('-added')[:5]
		# Ed ora prendiamo tutti i padri
		ancestors = [];
		thenode = self.get_object()
		while thenode:
			ancestors.append(thenode)
			thenode = thenode.parent
		context['ancestors'] = reversed(ancestors);
		return context

class NodeCreate(CreateView):
	model = Node
	template_name_suffix = '_create_form'

	def get_initial(self):
		initial = super(NodeCreate, self).get_initial()
		initial['parent'] = get_object_or_404(Node, pk=self.kwargs.get('father'))
		return initial
	
	def get_success_url(self):
		return reverse('tree:ShowNode', kwargs={'pk': self.kwargs.get('father')})
	
class NodeUpdate(UpdateView):
	model = Node
	template_name_suffix = '_update_form'

	def get_success_url(self):
		return reverse('tree:ShowNode', kwargs={'pk': self.get_object().id})

class NodeDelete(DeleteView):
	model = Node
	
	def get_success_url(self):
		return reverse('tree:ShowNode', kwargs={'pk': self.get_object().parent.id})


class LinkCreate(CreateView):
	model = Link
	template_name_suffix = '_create_form'

	def get_initial(self):
		initial = super(LinkCreate, self).get_initial()
		initial['nodes'] = Node.objects.filter(pk=self.kwargs.get('next'))
		return initial

	def get_success_url(self):
		return reverse('tree:ShowNode', kwargs={'pk': self.kwargs.get('next')})

class LinkUpdate(UpdateView):
	model = Link
	template_name_suffix = '_update_form'

	def get_success_url(self):
		return reverse('tree:ShowNode', kwargs={'pk': self.kwargs.get('next')})

class LinkDelete(DeleteView):
	model = Link
	
	def get_success_url(self):
		return reverse('tree:ShowNode', kwargs={'pk': self.kwargs.get('next')})

class TagCreate(CreateView):
	model = Tag
	template_name_suffix = '_create_form'

	def get_success_url(self):
		return reverse('tree:ShowNode', kwargs={'pk': self.kwargs.get('next')})

tree/templates/tree/link_confirm_delete.html
<form action="" method="post">
	{% csrf_token %}
	<p>Sei sicuro di voler eliminare "{{ object }}"?</p>
	<input type="submit" value="Conferma"/>
</form>

tree/templates/tree/link_create_form.html
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value"Crea link"/>
</form>

tree/templates/tree/link_inner.html
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title pull-left"><a href="{{ link.link }}" target="_blank">{{ link.name }}</a></h3>
		{% if user.is_authenticated %}
			<a href="{% url 'tree:LinkUpdate' link.id curnode.id %}"><button class="btn btn-default pull-right">Modifica Link</button></a>
			<a href="{% url 'tree:LinkDelete' link.id curnode.id %}"><button class="btn btn-default pull-right">Elimina Link</button></a>
		{% endif %}
		{% for t in link.tags.all %}
			<span class="label label-default pull-right little-margin">{{ t.name }}</span>
		{% endfor %}
		<div class="clearfix"></div>
	</div>
	<div class="panel-body">
		{{ link.description }}
	</div>
</div>

tree/templates/tree/link_update_form.html
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Update" />
</form>

tree/templates/tree/node_confirm_delete.html
<form action="" method="post">
	{% csrf_token %}
	<p>Sei sicuro di voler eliminare "{{ object }}"?</p>
	<input type="submit" value="Conferma"/>
</form>

tree/templates/tree/node_create_form.html
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value"Crea nodo"/>
</form>

tree/templates/tree/node_detail.html
{% load staticfiles %}
<html>
	<head>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
		<link rel="icon" type="image/png" href="{% static 'tree/favicon.png' %}"/>
		<link rel="stylesheet" href="{% static 'tree/custom-glyphs.css' %}"/>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
		<script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script>
		<script type="text/x-mathjax-config">
			MathJax.Hub.Config({tex2jax: {inlineMath: [['$', '$'], ['\\(', '\\)']]}});
		</script>
		<title>MA3 - {{ node.name }}</title>
	</head>
	<body>

	<div class="container-fluid">
		<div class="col-lg-2 col-md-3">
			<nav class="bs-docs-sidebar">
				{% if ancestors %}
					<h4>Ancestors</h4>
					<ul class="nav">
					{% for anode in ancestors %}
						<li><a href="{% url 'tree:ShowNode' anode.id %}">{{ anode.name }}</a></li>
					{% endfor %} 
					</ul>
				{% endif %}
				{% if user.is_authenticated %}
					<h4>Admin Tools</h4>
					<ul class="nav">
						<li><a href="{% url 'tree:NodeCreate' node.id %}">Aggiungi sottonodo</a></li>
						<li><a href="{% url 'tree:NodeUpdate' node.id %}">Modifica nodo</a></li>
						<li><a href="{% url 'tree:NodeDelete' node.id %}">Elimina nodo corrente</a></li>
						<li><a href="{% url 'tree:LinkCreate' node.id %}">Aggiungi link</a></li>
						<li><a href="{% url 'tree:TagCreate' node.id %}">Aggiungi un tag</a></li>
						<li><a href="{% url 'logout' %}">Logout</a></li>
					</ul>
				{% endif %}
				{% if latest_added %}
					<div class="hidden-sm-down">
						<h4>Last Added</h4>
						<ul class="nav">
							{% for i in latest_added %}
							<li><a href="{{ i.link }}">{{ i.name }}</a></li>
							{% endfor %}
						</ul>
					</div>
				{% endif %}
			</nav>
		</div>
		<div class="col-lg-10 col-md-9">
			
			<div class="page-header" style="text-align: center;">
				<h1>{{ node.name }}</h1>
			</div>

			<div class="panel panel-default">
				<div class="panel-body">
					{{ node.text }}
				</div>
			</div>

		{% if node.children %}
			<div class="row" style="margin-bottom: 25px;">
				{% for child in node.children.all %}
					{% include "tree/node_inner.html" with subnode=child %}
				{% endfor %}
			</div>
		{% endif %}

		{% if node.links %}
			{% for link in node.links.all %}
				{% include "tree/link_inner.html" with link=link curnode=node %}
			{% endfor %}
		{% endif %}
		</div>
		</div>
	</body>
</html>

tree/templates/tree/node_inner.html
<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
	<div class="row" style="margin: 10px 0px;">
		<a class="btn btn-default col-lg-10 col-md-10 col-sm-10 col-xs-12 col-lg-offset-1 col-md-offset-1 col-sm-offset-1"
			href="{% url 'tree:ShowNode' subnode.id %}">{{ subnode.name }}</a>
	</div>
</div>

tree/templates/tree/node_list.html
<h1>Nodes to go to</h1>
<ul>
{% for node in object_list %}
	<li><a href="{% url 'tree:ShowNode' node.id %}">{{ node.name }}</a></li>
{% empty %}
	<li><a href="{% url 'admin:login' %}">Non ci sono nodi, loggati</a></li>		
{% endfor %}
</ul>

tree/templates/tree/node_update_form.html
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Update" />
</form>

tree/templates/tree/tag_create_form.html
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value"Crea tag"/>
</form>